In [20]:
import numpy as np 
import torch 
import torch.nn as nn 

# 1. Affine transformation for fully-connected layer 
* model =```nn.Linear(input_node, output_node)```
    > ```n_input```: the number of nodes of input <br/>
    > ```n_output```: the number of nodes of output
* model```.weight``` : get model weights 
* model```.bias``` : get model bias 
* model```.parameters()```: get all model parameters

In [21]:
def Affine_model(n_input: int, n_output: int):
    model = nn.Linear(n_input, n_output)
    return model 

***

In [16]:
# _Start: Load data 
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]    # target label 
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]    # input 
t_c = torch.tensor(t_c).unsqueeze(1) # <1>
t_u = torch.tensor(t_u).unsqueeze(1) # <1>
# _End: Load data 

t_u.shape

torch.Size([11, 1])

In [15]:
# _Start: Shuffle trainig set and validation set 
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)   # 20% of the total samples 


shuffled_indices = torch.randperm(n_samples)  # shuffle the indices 
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

t_c_train = t_c[train_indices]
t_u_train = t_u[train_indices]

t_c_val  = t_c[val_indices]
t_u_val  = t_u[val_indices]
# _End: Shuffle trainig set and validation set 

print("********** < Data Shuffling: start > ***********")
print("Shuffled indices: ", shuffled_indices)
print("training indices: ", train_indices)
print("validation indices: ", val_indices)
print("********** < Data Shuffling: end > **********", end="\n\n")


# _Start: data standardization
t_un_train = 0.1 * t_u_train 
t_un_val   = 0.1 * t_u_val 
# _End: data standardization

print("Before: ", t_u_val)
print("After: ", t_un_val)

********** < Data Shuffling: start > ***********
Shuffled indices:  tensor([ 2,  7,  6,  3, 10,  8,  5,  9,  1,  4,  0])
training indices:  tensor([ 2,  7,  6,  3, 10,  8,  5,  9,  1])
validation indices:  tensor([4, 0])
********** < Data Shuffling: end > **********

Before:  tensor([[56.3000],
        [35.7000]])
After:  tensor([[5.6300],
        [3.5700]])


In [39]:
# _Start: instantiate your model and predict 
model = Affine_model(n_input=1, n_output=1) 
output = model(t_un_val)
# _End: instantiate your model and predict 

print(output, end="\n\n")


# _Start: take model parameters 
weights = model.weight 
bias   = model.bias 
parameters = model.parameters()
# _End: take model parameters 


print("********* < Model inspection: start > ************")
print("weights: ", weights, end="\n\n")
print("bias: ", bias, end="\n\n")
print("parameters: ", list(parameters))
print("********* < Model inspection: end > ************", end="\n\n")

tensor([[2.5892],
        [1.4110]], grad_fn=<AddmmBackward>)

********* < Model inspection: start > ************
weights:  Parameter containing:
tensor([[0.5719]], requires_grad=True)

bias:  Parameter containing:
tensor([-0.6309], requires_grad=True)

parameters:  [Parameter containing:
tensor([[0.5719]], requires_grad=True), Parameter containing:
tensor([-0.6309], requires_grad=True)]
********* < Model inspection: end > ************



In [35]:
# _Start: batch=1 input  
x = torch.ones(1)
out = model(x)
# _End: batch=1 input 


# _Start: batch=10 input 
x_batch = torch.ones(10, 1)
out_batch = model(x_batch)
# _End: batch=10 input 


print("batch=1 output: ", out.shape)
print("batch=10 output: ", out_batch.shape)

batch=1 output:  torch.Size([1])
batch=10 output:  torch.Size([10, 1])
